name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8', '3.8', '3.9']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dev requirements
        run: pip install -r requirements-dev.txt

      - name: Test with pytest
        run: pytest . 
  
  test-coverage:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
    
      - name: Install dev requirements
        run: pip install -r requirements-dev.txt

      - name: Generate coverage report
        run: pytest . --cov=thinkcell --cov-report=xml
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
       
